services:
  postgres_db:
    image: postgres:16.1-alpine
    container_name: lms_postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zenmonk
      POSTGRES_DB: ibms_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - lms_network

  redis:
    image: redis:7.2-alpine
    container_name: sso_redis
    networks:
      - lms_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: lms_pgadmin
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres_db
    networks:
      - lms_network

  dev-runner:
    container_name: lms_turbo_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "8080:8080"
      - "5555:5555"
    env_file:
      - ./apps/lms-backend/.env
      - ./apps/lms-frontend/.env
      - ./apps/single-sign-on/.env
    depends_on:
      - postgres_db
      - redis
    tty: true
    stdin_open: true
    networks:
      - lms_network
    command: sh -c "sleep infinity"


networks:
  lms_network:
    external: true
    name: leave-management-network

volumes:
  pg_data:
