version: "3.9"

services:
  database:
    image: postgres:16.1-alpine3.18
    container_name: lms-postgres
    restart: always
    ports:
      - ${DB_FORWARD_PORT:-5433}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_DATABASE:-lms}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - lms_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: lms-pgadmin
    restart: always
    ports:
      - ${PGADMIN_FORWARD_PORT:-8888}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - lms_network
    depends_on:
      - database

  redis:
    image: redis:7.2-alpine
    container_name: lms-redis
    restart: always
    ports:
      - ${REDIS_FORWARD_PORT:-6378}:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - lms_network

  lms-backend:
    container_name: lms-backend
    build:
      context: .
      dockerfile: ./apps/lms-backend/Dockerfile.dev
    env_file:
      - ./apps/lms-backend/.env.example
    ports:
      - "8080:8080"
    volumes:
      - ./apps/lms-backend:/app
      - /app/node_modules
    restart: on-failure
    tty: true
    stdin_open: true
    networks:
      - lms_network
    depends_on:
      - database

  single-sign-on:
    container_name: single-sign-on
    build:
      context: .
      dockerfile: ./apps/single-sign-on/Dockerfile.dev
    env_file:
      - ./apps/single-sign-on/.env.example
    ports:
      - "5555:5555"
    volumes:
      - ./apps/single-sign-on:/app
      - /app/node_modules
    restart: on-failure
    tty: true
    stdin_open: true
    networks:
      - lms_network
    depends_on:
      - database
      - redis

  lms-frontend:
    container_name: lms-frontend
    build:
      context: .
      dockerfile: ./apps/lms-frontend/Dockerfile.dev
    env_file:
      - ./apps/lms-frontend/.env.example
    ports:
      - "3000:3000"
    volumes:
      - ./apps/lms-frontend:/app
      - /app/node_modules
    restart: on-failure
    tty: true
    stdin_open: true
    networks:
      - lms_network
    depends_on:
      - lms-backend
      - single-sign-on


networks:
  lms_network:
    name: lms-shared-network
    external: true

volumes:
  pg_data: {}
  pgadmin_data: {}
  redis_data: {}
